# general settings
# Please modify model_type according to your needs.
name: 00_GDSR_x3_aid_bic_Wavelet
model_type: WaveletSRModel
# model_type: SRModel 
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: dataset_aid_bic_x3
    type: PairedImageDataset
    dataroot_gt: datasets/dataset_aid_bic_x3/train/HR.lmdb
    dataroot_lq: datasets/dataset_aid_bic_x3/train/LR.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1

  val:
    name: dataset_aid_val_bic_x3
    type: PairedImageDataset
    dataroot_gt: datasets/dataset_aid_bic_x3/val/HR
    dataroot_lq: datasets/dataset_aid_bic_x3/val/LR
    io_backend:
      type: disk

# network structures
# Please modify rgb_mean according to your needs.
network_g:
  type: GDSR
  upscale: 3
  in_chans: 3
  img_size: 64
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 96
  mlp_ratio: 4.
  RCB_num: 12
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  rgb_mean: [0.39554116,0.40749934,0.36668935]

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000]
    gamma: 0.5 

  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  swt_opt:
    type: SWTLoss
    loss_weight_l: 0.05
    loss_weight_h: 0.01
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 3
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: false